Remove redundant code
apple/cups pull request #5953
Opened 2021-09-03 14:52 UTC by AtariDreams

Some of the code is either dead code, redundant, or always true. Meaning they do not do anything since the cases were already dealt with in earlier parts of the code. It would be best to remove this code.

Note that some of the code removal required a tiny bit of refactoring.

2021-09-05 12:35 UTC, michaelrsweet requested changes
In general this looks good. You need to leave the NULL function checks in place since on macOS looking for the address of a function is a way to detect the presence of an optional ("weak linked") library.

2021-09-05 12:35 UTC, michaelrsweet commented on cups/auth.c
> -#  ifdef __APPLE__
This code cannot be removed as it is necessary for libcups to work on macOS when running without the Kerberos library (mainly in the installer).

2021-09-05 12:35 UTC, michaelrsweet commented on scheduler/auth.c
> -
Same as for cups/auth.c. Can't be removed without breaking things on macOS.

2021-09-05 12:35 UTC, michaelrsweet commented on scheduler/colorman.c
> -  if (&ColorSyncRegisterDevice == NULL)
Ditto.

2021-09-05 12:35 UTC, michaelrsweet commented on scheduler/conf.c
> -  */
Ditto.

2021-09-05 12:35 UTC, michaelrsweet commented on scheduler/ipp.c
> +
Please don't introduce goto's for this. The only time we use goto is for a simple form of exception handling at the bottom of a function.

2021-09-05 12:35 UTC, michaelrsweet commented on systemv/lpstat.c
> +  } while (*list);
Coding style - the while should appear on a line after the closing brace...

2021-09-06 17:43 UTC, AtariDreams commented
All issues addressed!

2021-09-07 16:32 UTC, merged